Question 2
If, in the code for one of your methods (call it method1), you invoke another method that throws a checked exception, what are the two options available to you for handling the exception in your method1?

